// swift-tools-version: 5.6

// DO NOT MODIFY
// Automatically generated by Arkana (https://github.com/rogerluan/arkana)

import PackageDescription

let package = Package(
    name: "WeatherAppSecrets",
    platforms: [
        .macOS(.v11),
        .iOS(.v11),
        .tvOS(.v11),
        .watchOS(.v4),
    ],
    products: [
        .library(
            name: "WeatherAppSecrets",
            targets: ["WeatherAppSecrets"]
        ),
    ],
    dependencies: [
        .package(name: "WeatherAppSecretsInterfaces", path: "../WeatherAppSecretsInterfaces"),
    ],
    targets: [
        .target(
            name: "WeatherAppSecrets",
            dependencies: ["WeatherAppSecretsInterfaces"],
            path: "Sources"
        ),
        .testTarget(
            name: "WeatherAppSecretsTests",
            dependencies: ["WeatherAppSecrets"],
            path: "Tests"
        ),
    ]
)
