// swift-tools-version: 5.6

// DO NOT MODIFY
// Automatically generated by Arkana (https://github.com/rogerluan/arkana)

import PackageDescription

let package = Package(
    name: "WeatherAppSecretsInterfaces",
    platforms: [
        .macOS(.v11),
        .iOS(.v11),
        .tvOS(.v11),
        .watchOS(.v4),
    ],
    products: [
        .library(
            name: "WeatherAppSecretsInterfaces",
            targets: ["WeatherAppSecretsInterfaces"]
        ),
    ],
    dependencies: [],
    targets: [
        .target(
            name: "WeatherAppSecretsInterfaces",
            dependencies: [],
            path: "Sources"
        ),
    ]
)
