// DO NOT MODIFY
// Automatically generated by Arkana (https://github.com/rogerluan/arkana)

import Foundation

// MARK: - WeatherAppSecretsGlobalProtocol

public protocol WeatherAppSecretsGlobalProtocol { }

// MARK: - WeatherAppSecretsEnvironmentProtocol

public protocol WeatherAppSecretsEnvironmentProtocol {
    var baseURL: String { get }
    var apiKey: String { get }
}
